server:
  port: 8092
spring:
  profiles:
    active: dev
    group:
      dev:
        - stock
  datasource:
    url: jdbc:mysql://172.16.39.131:3306/stock_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.ming.stock.pojo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true




